"""Format computed study results as manuscript tables. No statistical inference."""
from __future__ import annotations
from typing import Any
from .regression_format import interval_cell, source_key, validate_feature_inventory, PROVIDERS
FAMILIES: dict[str, dict[str, Any]] = {
    "arithmetic24": {
        "name": "Arithmetic",
        "slug": "arithmetic",
        "features": (
            "normalized_minimum_division_count",
            "balanced_plan_affordance",
            "normalized_minimum_display_order_inversions",
        ),
        "headers": (r"\mathrm{div}", r"\mathrm{bal}", r"\mathrm{inv}"),
    },
    "grid_placement": {
        "name": "Rooks",
        "slug": "grid",
        "features": (
            "normalized_mean_marginal_cell_rarity",
            "normalized_symmetric_monotonicity_penalty",
            "normalized_column_sequence_direction_changes",
        ),
        "headers": (r"\mathrm{rarity}", r"\mathrm{mono}", r"\mathrm{change}"),
    },
    "minesweeper_lite": {
        "name": "Minesweeper",
        "slug": "minesweeper",
        "features": (
            "normalized_minimum_certificate_size",
            "normalized_minimum_certificate_scope",
        ),
        "headers": (r"\mathrm{size}", r"\mathrm{scope}"),
    },
    "mini_sudoku": {
        "name": "Sudoku",
        "slug": "sudoku",
        "features": (
            "normalized_cell_domain_size",
            "normalized_target_location_count",
        ),
        "headers": (r"\mathrm{domain}", r"\mathrm{location}"),
    },
}

def coefficient_cell(fit: dict[str, Any], feature: str) -> str:
    return interval_cell(
        fit["feature_coefficients"][feature],
        fit["feature_coefficient_ci_95"][feature],
        bold_if_excludes_zero=True,
    )

def accuracy_cell(fit: dict[str, Any], choice: bool) -> str:
    if choice:
        point = "cv_top_choice_accuracy"
        interval = "cv_top_choice_accuracy_ci_95"
    else:
        point = "cv_balanced_accuracy"
        interval = "cv_balanced_accuracy_ci_95"
    return interval_cell(fit[point], fit[interval])

def primary_table(
    *,
    caption: str,
    label: str,
    fits: list[tuple[str, dict[str, Any]]],
    features: tuple[str, ...],
    feature_headers: tuple[str, ...],
    choice: bool,
) -> list[str]:
    coefficient_symbol = r"\widehat{\theta}" if choice else r"\widehat{\beta}"
    headers = [
        rf"${coefficient_symbol}_{{{header}}}$" for header in feature_headers
    ]
    source_header = "Source" if choice else "Model/Human"
    lines = [
        r"\begin{table}[H]",
        f"  \\caption{{{caption}}}",
        f"  \\label{{{label}}}",
        r"  \centering",
        r"  \regressiontableformat",
        f"  \\begin{{tabular}}{{@{{}}l{'r' * (len(features) + 1)}@{{}}}}",
        r"    \toprule",
        "    "
        + " & ".join((
            source_header,
            *headers,
            "Acc." if choice else "BA",
        ))
        + r" \\",
        r"    \midrule",
    ]
    for source, fit in fits:
        cells = [source]
        cells.extend(coefficient_cell(fit, feature) for feature in features)
        cells.append(accuracy_cell(fit, choice))
        lines.append("    " + " & ".join(cells) + r" \\")
    lines.extend([r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""])
    return lines

def render_primary(data: dict[str, Any]) -> str:
    family = str(data["family"])
    config = FAMILIES[family]
    name = config["name"]
    slug = config["slug"]
    features = tuple(config["features"])
    validate_feature_inventory(data, features, name)
    selected = data["selected_solution_prediction"]["conditional"]["fits"]
    binary = data["source_prediction"]["binary_vs_human"]["conditional"]["fits"]
    choice_fits = [("Human", selected["Human"])] + [
        (display, selected[source_key(provider, "low", "plain")])
        for provider, display in PROVIDERS
    ]
    source_fits = [
        (display, binary[source_key(provider, "low", "plain")])
        for provider, display in PROVIDERS
    ]
    lines = [
        "% Generated by figures/tables_regression.py.",
        "% Model rows use only the primary low-effort, plain-prompt condition.",
    ]
    lines.extend(primary_table(
        caption=f"Selected-solution {name} regressions.",
        label=f"tab:{slug}-choice-results",
        fits=choice_fits,
        features=features,
        feature_headers=tuple(config["headers"]),
        choice=True,
    ))
    lines.extend(primary_table(
        caption=f"Source classification for {name}.",
        label=f"tab:{slug}-source-binary-results",
        fits=source_fits,
        features=features,
        feature_headers=tuple(config["headers"]),
        choice=False,
    ))
    return "\n".join(lines)
