"""Format the selected three-feature Maze regressions."""
from .regression_format import interval_cell, validate_feature_inventory
FEATURES = ['turn_count', 'background_edge_load', 'mean_centered_goal_distance']
def render(data):
    validate_feature_inventory(data, tuple(FEATURES), 'Maze')
    assert data['bootstrap_repeats'] == 2000
    assert data['constant_feature_replacement'] == 'training_mean'
    fits = data['fits']
    assert len(fits['choice']) == 4 and len(fits['source']) == 3
    lines = ['% Three-feature Maze tables; generated by make_combined_tables.py.']
    for task in ['choice', 'source']:
        sources = ['Human', 'ChatGPT', 'Claude', 'Gemini'] if task=='choice' else ['ChatGPT', 'Claude', 'Gemini']
        label = 'tab:maze-choice-results' if task=='choice' else 'tab:maze-source-binary-results'
        symbol = 'theta' if task=='choice' else 'beta'
        metric = 'cv_top_choice_accuracy' if task=='choice' else 'cv_balanced_accuracy'
        caption = ('Selected-solution Maze regressions' if task=='choice' else 'Source classification for Maze')
        caption += '.'
        headers = [r'$\widehat{'+'\\'+symbol+r'}_{\mathrm{'+name+r'}}$' for name in ['turn','edge','rel']]
        lines += [r'\begin{table}[H]', r'\caption{'+caption+'}',
                  r'\label{'+label+'}', r'\label{tab:maze-extended-'+task+'}', r'\centering', r'\regressiontableformat',
                  r'\begin{tabular}{@{}lrrrr@{}}', r'\toprule',
                  ('Source' if task=='choice' else 'Model/Human')+' & '+' & '.join(headers)+
                  (' & Acc.' if task=='choice' else ' & BA')+r' \\',
                  r'\midrule']
        for source in sources:
            fit = fits[task][source]
            assert fit['bootstrap_validation_repeats'] == 2000
            values = [source]+[interval_cell(fit['feature_coefficients'][f],fit['feature_coefficient_ci_95'][f],bold_if_excludes_zero=True) for f in FEATURES]
            values.append(interval_cell(fit[metric],fit[metric+'_ci_95']))
            lines.append(' & '.join(values)+r' \\')
        lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
    return '\n'.join(lines)
